In [321]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [322]:
from sklearn.datasets import load_iris

iris = load_iris()
X = iris["data"][:, 3:]
y = iris["target"]
X_with_bias = np.c_[np.ones([len(X), 1]), X]

In [323]:
def softmax_score(X, weights):
    return X @ weights

def softmax_func(scores):
    exp_scores = np.exp(scores)
    return exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

def softmax_classifier(probs):
    return np.argmax(probs, axis=1)

def x_entropy(probs):
    pass

def x_entropy_gradient(probs, X, y):
    return (1 / len(X)) * (X.T @ (probs - y))

In [324]:
def to_one_hot(y):
    n_classes = y.max() + 1
    m = len(y)
    Y_one_hot = np.zeros((m, n_classes))
    Y_one_hot[np.arange(m), y] = 1
    return Y_one_hot

In [325]:
y_to_one_hot = to_one_hot(y)

In [326]:
class MySoftmaxRegression():

    iterations = 1000
    learning_rate = 0.5
    weigths = None

    def fit(self, X, y):
        weights = np.zeros((X.shape[1], y.shape[1]))    
        for i in range(self.iterations):
            scores = softmax_score(X, weights)
            probs = softmax_func(scores)
            weights -= self.learning_rate * x_entropy_gradient(probs, X, y)
        self.weights = weights
        print(weights)
        return weights

    def predict(self, X):
        scores = softmax_score(X, self.weights)
        probs = softmax_func(scores)
        return softmax_classifier(probs)
            


In [327]:
softmax = MySoftmaxRegression()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_with_bias, y_to_one_hot, test_size=0.2, random_state=42)

softmax.fit(X_train, y_train)

y_pred = softmax.predict(X_test)
y_test_labels = np.argmax(y_test, axis=1)
accuracy = np.mean(y_pred == y_test_labels)
print(f"Accuracy: {accuracy:.2f}")

[[ 6.75576934  1.40957791 -8.16534725]
 [-6.95325362  0.53318029  6.42007333]]
Accuracy: 1.00


In [328]:
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)

X_train, X_test, y_train, y_test = train_test_split(X_with_bias, y, test_size=0.2, random_state=42)
# Train the model
model.fit(X_train, y_train)
print(model.coef_)

# Make predictions
predictions = model.predict(X_test)

# Evaluate the model (e.g., accuracy)
accuracy = model.score(X_test, y_test)
print(f"Model accuracy: {accuracy}")

[[-2.27266364e-04 -3.94196871e+00]
 [-9.63558579e-05  1.32991023e-01]
 [ 3.23622222e-04  3.80897769e+00]]
Model accuracy: 1.0


/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


In [336]:
import numpy as np

def to_categorical(x, n_col=None):
    n_col = np.max(x)
    one_hot_encoded = np.zeros((x.shape[0], n_col + 1))
    print(one_hot_encoded)
    for i in range(x.shape[0]):
        one_hot_encoded[i, x[i]] = 1
    return one_hot_encoded

x = np.array([0, 1, 2, 1, 0])
output = to_categorical(x)
print(output)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
